
import { Vehicle, Driver, VehicleStatus, DriverStatus, Route, PurchaseOrder, Shipment, ConfirmedShipment, Appointment } from './types';

export const INITIAL_VEHICLES: Vehicle[] = [
  { 
    id: 'v1', 
    name: 'Truck A-101', 
    type: 'Heavy Freight', 
    plate: 'KY-5592', 
    status: VehicleStatus.IN_TRANSIT, 
    fuelLevel: 72, 
    driverId: 'd1', 
    location: 'En route to Chicago', 
    destination: 'Chicago, IL', 
    coordinates: { x: 200, y: 300 },
    attachments: [
      { id: 'a1', type: 'NOTE', content: 'Scheduled for oil change next week.', timestamp: '2023-10-25T10:00:00Z' },
      { id: 'a2', type: 'DOCUMENT', content: 'Manifest_CHI_001.pdf', timestamp: '2023-10-26T08:30:00Z' }
    ]
  },
  { 
    id: 'v2', 
    name: 'Van B-205', 
    type: 'Last Mile Van', 
    plate: 'NY-2210', 
    status: VehicleStatus.IDLE, 
    fuelLevel: 95, 
    driverId: 'd2', 
    location: 'Depot NYC', 
    coordinates: { x: 800, y: 150 },
    attachments: []
  },
  { 
    id: 'v3', 
    name: 'Truck A-104', 
    type: 'Heavy Freight', 
    plate: 'TX-9931', 
    status: VehicleStatus.MAINTENANCE, 
    fuelLevel: 15, 
    location: 'Service Center', 
    coordinates: { x: 400, y: 500 },
    attachments: [
      { id: 'a3', type: 'NOTE', content: 'Engine light reported by driver.', timestamp: '2023-10-27T14:15:00Z' }
    ]
  },
  { 
    id: 'v4', 
    name: 'Truck C-303', 
    type: 'Refrigerated', 
    plate: 'CA-4421', 
    status: VehicleStatus.IN_TRANSIT, 
    fuelLevel: 45, 
    driverId: 'd3', 
    location: 'Passing Denver', 
    destination: 'San Francisco, CA', 
    coordinates: { x: 300, y: 400 },
    attachments: []
  },
  { 
    id: 'v5', 
    name: 'Van B-208', 
    type: 'Last Mile Van', 
    plate: 'WA-1102', 
    status: VehicleStatus.IN_TRANSIT, 
    fuelLevel: 60, 
    driverId: 'd4', 
    location: 'Downtown Seattle', 
    destination: 'Seattle, WA', 
    coordinates: { x: 100, y: 100 },
    attachments: []
  },
];

export const INITIAL_DRIVERS: Driver[] = [
  { 
    id: 'd1', 
    name: 'Geraldi Spaho', 
    license: '1092399', 
    status: DriverStatus.AVAILABLE, 
    rating: 5.0, 
    totalTrips: 60,
    email: 'electronics.things_al@outlook.com',
    phone: '+355676430573',
    age: 60,
    licenseState: 'CA',
    licenseExpiration: '2028-12-22',
    trailerNumber: 'ML-0990q'
  },
  { id: 'd2', name: 'Sarah Connor', license: 'Class C', status: DriverStatus.AVAILABLE, rating: 5.0, totalTrips: 89, phone: '555-0102' },
  { id: 'd3', name: 'Mike Ross', license: 'CDL-A', status: DriverStatus.ON_DUTY, rating: 4.5, totalTrips: 210, phone: '555-0103' },
  { id: 'd4', name: 'Rachel Zane', license: 'Class C', status: DriverStatus.ON_DUTY, rating: 4.9, totalTrips: 56, phone: '555-0104' },
  { id: 'd5', name: 'Harvey Specter', license: 'CDL-A', status: DriverStatus.OFF_DUTY, rating: 4.7, totalTrips: 340, phone: '555-0105' },
];

export const MOCK_ROUTES: Route[] = [
  { id: 'r1', vehicleId: 'v1', origin: 'New York', destination: 'Chicago', stops: ['Cleveland', 'Toledo'], distance: 1200, estimatedTime: '18h', status: 'ACTIVE' },
  { id: 'r2', vehicleId: 'v4', origin: 'Dallas', destination: 'San Francisco', stops: ['Albuquerque', 'Las Vegas'], distance: 2400, estimatedTime: '32h', status: 'ACTIVE' },
];

export const MOCK_PURCHASE_ORDERS: PurchaseOrder[] = [
  { 
    id: '15915945', 
    supplier: 'ORLY SHOE CORPORATION', 
    date: '2025-05-16', 
    status: 'Closed', 
    totalAmount: 0, 
    items: 8520, 
    expectedDelivery: '2025-06-03', 
    dcAddress: 'Bloomington, CA, 92316',
    poType: 'Domestic',
    paymentTerms: 'Net90',
    buyer: ' ',
    cancelDate: '2025-06-03'
  },
  { 
    id: '78945612', 
    supplier: 'ORLY SHOE CORPORATION', 
    date: '2025-05-19', 
    status: 'Closed', 
    totalAmount: 0, 
    items: 9000, 
    expectedDelivery: '2025-05-26', 
    dcAddress: 'Bloomington, CA, 92316',
    poType: 'Domestic',
    paymentTerms: 'Net90',
    buyer: ' ',
    cancelDate: '2025-05-26'
  },
  { 
    id: '75210321', 
    supplier: 'ORLY SHOE CORPORATION', 
    date: '2025-05-15', 
    status: 'Closed', 
    totalAmount: 0, 
    items: 855, 
    expectedDelivery: '2025-05-30', 
    dcAddress: 'Bloomington, CA, 92316',
    poType: 'Domestic',
    paymentTerms: 'Net90',
    buyer: ' ',
    cancelDate: '2025-05-30'
  },
  { 
    id: '12345690', 
    supplier: 'GERIAN', 
    date: '2025-09-29', 
    status: 'PENDING', // Using PENDING as proxy for empty status in CSV
    totalAmount: 0, 
    items: 1200, 
    expectedDelivery: '2025-10-06', 
    dcName: 'CONNECTICUT DC', 
    dcAddress: '89, newohone 06705', 
    fobPointName: 'RIALTO',
    poType: 'Domestic',
    paymentTerms: 'Net30',
    priority: 'Yes',
    buyer: 'JOSEPH',
    cancelDate: '2025-10-10',
    incoterms: 'DDP'
  },
  {
    id: '12340000',
    supplier: 'AREN',
    date: '2025-09-26',
    status: 'Closed',
    totalAmount: 0,
    items: 1200,
    expectedDelivery: '2025-10-01',
    dcName: 'CONNECTICUT DC',
    dcAddress: '89, newohone 06705',
    fobPointName: 'RIALTO',
    poType: 'Domestic',
    paymentTerms: 'Net90',
    buyer: 'JOSEPH',
    cancelDate: '2025-10-08',
    incoterms: 'EXW'
  }
];

export const MOCK_SHIPMENTS: Shipment[] = [
  { 
    id: 'SHP-272019', 
    trackingId: 'TRK-272019', 
    purchaseOrderId: '75210321', 
    vendorName: 'ORLY SHOE CORPORATION', 
    pickupLocation: 'Mt Pocono, PA 18344', 
    deliveryAddress: 'Bloomington, CA, 92316', 
    origin: 'Mt Pocono, PA', 
    destination: 'Bloomington, CA', 
    status: 'Closed', 
    estimatedArrival: '2025-05-26', 
    carrier: 'Nexus Fleet', 
    freightType: 'Dry', 
    totalUnits: 9780, 
    totalCartons: 163, 
    totalPallets: 6, 
    totalWeight: 2856, 
    totalCubicFeet: 522,
    palletized: true, 
    stackable: false, 
    palletType: 'Standard', 
    liftGate: false, limitedAccess: false, immediatePickup: false, residentialLocation: false, 
    callForAppointment: false, insideDelivery: false, onTimeGuaranteed: false, temperatureControl: false, fragile: false,
    agingDays: 0,
    shipmentCondition: 'Okay',
    submittedDate: '2025-05-26'
  },
  { 
    id: 'SHP-332003', 
    trackingId: 'TRK-332003', 
    purchaseOrderId: '', 
    vendorName: 'ORLY SHOE CORPORATION', 
    pickupLocation: 'Mt Pocono, PA 18344', 
    deliveryAddress: 'Bloomington, CA, 92316', 
    origin: 'Mt Pocono, PA', 
    destination: 'Bloomington, CA', 
    status: 'Closed', 
    estimatedArrival: '', 
    carrier: 'Nexus Fleet', 
    freightType: 'Dry', 
    totalUnits: 960, 
    totalCartons: 16, 
    totalPallets: 1, 
    totalWeight: 320, 
    palletDimensions: '48x40x59',
    palletized: true, 
    stackable: false, 
    palletType: 'Standard', 
    liftGate: false, limitedAccess: false, immediatePickup: false, residentialLocation: false, 
    callForAppointment: false, insideDelivery: false, onTimeGuaranteed: false, temperatureControl: false, fragile: false,
    agingDays: 0,
    shipmentCondition: 'Okay'
  },
  { 
    id: 'SHP-453145', 
    trackingId: 'TRK-453145', 
    purchaseOrderId: '', 
    vendorName: 'ORLY SHOE CORPORATION', 
    pickupLocation: 'OLLIE DC, TX 70910', 
    deliveryAddress: '855 W Valley Blvd, Bloomington, CA 92316', 
    origin: 'OLLIE DC, TX', 
    destination: 'Bloomington, CA', 
    status: 'ROUTED', 
    estimatedArrival: '', 
    carrier: 'Nexus Fleet', 
    freightType: 'Dry', 
    totalUnits: 6000, 
    totalCartons: 100, 
    totalPallets: 5, 
    totalWeight: 2350, 
    palletDimensions: '48x40x90',
    palletized: true, 
    stackable: false, 
    palletType: 'Standard', 
    liftGate: false, limitedAccess: false, immediatePickup: false, residentialLocation: false, 
    callForAppointment: false, insideDelivery: false, onTimeGuaranteed: false, temperatureControl: false, fragile: false,
    agingDays: 0,
    shipmentCondition: 'Okay'
  },
  { 
    id: 'SHP-893081', 
    trackingId: 'TRK-893081', 
    purchaseOrderId: '12340000', 
    vendorName: 'AREN', 
    pickupLocation: '89, newohone 06705', 
    deliveryAddress: '89, newohone 06705', 
    origin: '89, newohone 06705', 
    destination: '89, newohone 06705', 
    status: 'Closed', 
    estimatedArrival: '2025-09-26', 
    carrier: 'Nexus Fleet', 
    freightType: 'Dry', 
    totalUnits: 1200, 
    totalCartons: 20, 
    totalPallets: 1, 
    totalWeight: 450, 
    palletDimensions: '48x40x80',
    palletized: true, 
    stackable: false, 
    palletType: 'Standard', 
    liftGate: false, limitedAccess: false, immediatePickup: false, residentialLocation: false, 
    callForAppointment: false, insideDelivery: false, onTimeGuaranteed: false, temperatureControl: false, fragile: false,
    agingDays: 0,
    shipmentCondition: 'Okay',
    submittedDate: '2025-09-26',
    submittedByUser: 'electronics.things_al@outlook.com'
  }
];

export const MOCK_CONFIRMED_SHIPMENTS: ConfirmedShipment[] = [
  { 
    id: '1000000036', 
    shipmentId: 'SHP-272019', 
    deliveryDate: '2025-06-02', 
    signedBy: 'Unknown', 
    condition: 'GOOD',
    transportStatus: 'Delivered',
    asnStatus: 'Sent',
    freightCost: 900.0,
    freightTerms: 'Collect', // CSV has empty but implies
    totalCartons: 142,
    totalPallets: 6,
    totalWeight: 2830,
    totalCubicFeet: 454,
    createdDate: '2025-05-26',
    scheduledDeliveryDate: '2025-06-04'
  } as unknown as ConfirmedShipment, // force type for partial mock
  { 
    id: '1000000039', 
    shipmentId: 'SHP-288024', 
    deliveryDate: '2025-06-04', 
    signedBy: 'Unknown', 
    condition: 'GOOD',
    transportStatus: 'Delivered',
    asnStatus: 'Sent',
    freightTerms: 'Collect',
    shipFromAddress: 'mt pocono, Pennsylvania 18344',
    currentLocationAddress: 'mt pocono',
    currentLocationState: 'Pennsylvania',
    currentLocationLatitude: '41.1221',
    currentLocationLongitude: '-75.3647',
    totalCartons: 37,
    totalPallets: 2,
    totalWeight: 780,
    totalCubicFeet: 120,
    expenseRecorded: true,
    createdDate: '2025-05-29',
    scheduledDeliveryDate: '2025-06-06'
  } as unknown as ConfirmedShipment,
  {
    id: '1000000137',
    shipmentId: 'SHP-486124',
    deliveryDate: '2025-07-16',
    signedBy: 'Unknown',
    condition: 'GOOD',
    transportStatus: 'Delivered',
    asnStatus: 'Sent',
    freightCost: 800.0,
    freightTerms: 'Collect',
    shipFromAddress: '855 W Valley Blvd, Bloomington, CA 92316',
    shipToAddress: 'ROSS DC EAST, 17013',
    carrierEmail: 'electronics.things_al@outlook.com',
    bolNumber: '87654324',
    trailerNumber: 'YT-98',
    driverName: '348900',
    scacCode: 'TQYL',
    transportationMode: 'Truck',
    totalCartons: 630,
    totalPallets: 23,
    totalWeight: 14500,
    totalCubicFeet: 2020,
    createdDate: '2025-07-12',
    scheduledDeliveryDate: '2025-07-17'
  } as unknown as ConfirmedShipment,
  {
    id: '1000000159',
    shipmentId: 'SHP-745049',
    deliveryDate: '2025-08-25',
    signedBy: 'Unknown',
    condition: 'GOOD',
    transportStatus: 'Delivered',
    asnStatus: 'Sent',
    freightCost: 2400.0,
    freightTerms: 'Collect',
    shipFromAddress: '176451000000517003', // Should map to name
    shipToAddress: '89, newohone 06705',
    carrierEmail: 'electronics.things_al@outlook.com',
    bolNumber: '71910982980',
    trailerNumber: '238987',
    driverName: '7868759',
    scacCode: 'MODE',
    transportationMode: 'Truck',
    totalCartons: 670,
    totalPallets: 25,
    totalWeight: 15500,
    totalCubicFeet: 2215,
    loadType: 'Full Truckload',
    trackingNumber: 'by-322444',
    createdDate: '2025-08-16',
    scheduledDeliveryDate: '2025-08-27'
  } as unknown as ConfirmedShipment
];

export const MOCK_APPOINTMENTS: Appointment[] = [
  { id: '100001', type: 'WAREHOUSE', date: '2025-07-23', time: '09:30', status: 'Completed', dockNumber: '7', address: '855 W Valley Blvd, Bloomington, CA 92316', cartons: 661, pallets: 24 },
  { id: '100002', type: 'WAREHOUSE', date: '2025-07-23', time: '11:00', status: 'Completed', dockNumber: ' ', address: '89, newohone 06705', cartons: 733, pallets: 26, scac: 'RBCG' },
  { id: '100007', type: 'WAREHOUSE', date: '2025-09-02', time: '10:30', status: 'Completed', dockNumber: '7', address: '855 W Valley Blvd', cartons: 191, pallets: 7 },
  { id: '100008', type: 'WAREHOUSE', date: '2025-09-02', time: '11:30', status: 'Completed', dockNumber: '7', address: '855 W Valley Blvd', cartons: 191, pallets: 7 },
  { id: '100018', type: 'PICKUP', date: '2025-09-30', time: '11:00', status: 'Completed', address: 'Bloomington, CA 92316', scac: 'CHR', cartons: 22, pallets: 1 },
  { id: '100019', type: 'PICKUP', date: '2025-10-08', time: '12:30', status: 'Completed', address: '943 MT POCONO, 18344', scac: 'RBCG', cartons: 20, pallets: 1 },
  { id: '100020', type: 'PICKUP', date: '2025-09-30', time: '13:00', status: 'Completed', address: 'MT POCONO', scac: 'CHR', cartons: 22, pallets: 1 }
];

// D3 Visualization Nodes
export const MAP_NODES = [
  { id: 'Seattle', x: 100, y: 100 },
  { id: 'SF', x: 100, y: 400 },
  { id: 'LA', x: 150, y: 550 },
  { id: 'Denver', x: 350, y: 350 },
  { id: 'Dallas', x: 450, y: 500 },
  { id: 'Chicago', x: 600, y: 250 },
  { id: 'NYC', x: 800, y: 200 },
  { id: 'Miami', x: 750, y: 600 },
];

export const MAP_LINKS = [
  { source: 'Seattle', target: 'SF' },
  { source: 'SF', target: 'LA' },
  { source: 'LA', target: 'Denver' },
  { source: 'Denver', target: 'Chicago' },
  { source: 'Chicago', target: 'NYC' },
  { source: 'NYC', target: 'Miami' },
  { source: 'Dallas', target: 'Miami' },
  { source: 'Dallas', target: 'Denver' },
  { source: 'Seattle', target: 'Chicago' },
];
